### ISSUE TITLE
Issues with build.sh

### ISSUE THREAD

**Issue by darkreapyre** [lucioveloso/cli2cloudformation#1]
When running ./build.sh I get the following error:

"cp: aws: No such file or directory"

Is this support to reference the installation of awscli or the 'wrapper' file?

**Comment by lucioveloso** [comment]
Hi,

I changed the cp command to the right  file and already committed.

Thank you.

**Comment by darkreapyre** [comment]
Thank you, that makes a lot more sense. By The Way  what you've done here is quite ingenious!
